apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
reclaimPolicy: Retain
provisioner: file.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
parameters: 
  skuName: Standard_LRS

