apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        command: ["mongod"] 
        args: ["--dbpath=/data/mongoaz", "--bind_ip_all"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-ps
          mountPath: /data/mongoaz
      volumes:
      - name: mongo-ps
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector: 
    app: mongodb
  ports:
    - protocol: TCP
      targetPort: 27017
      port: 27017



